export default interface Recipe {
  id: string,
  name: string,
  ingredients: string[],
  instructions: string[],
  prepTimeMinutes: number,
  cookTimeMinutes: number,
  servings: number,
  difficulty: string,
  cuisine: string,
  caloriesPerServing: number,
  tags: string[],
  userId: string,
  image: string,
  rating: number,
  reviewCount: number,
  mealType: string[],
}